import React from "react";
import Head from "next/head";
import Header from "../../../components/molecules/Header";
import Nav from "../../../components/molecules/Nav";
import styles from "../../../styles/Home.module.css";
import FormStyle from "../../../styles/forms.module.css";
import Button from "../../../components/atoms/Buttons";
import AddIcon from "../../../images/icons/AddIcon";
import {
  RoundedInput,
  RadioButtonContainer,
} from "../../../components/atoms/Input";

function modifieduser(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>MCP- Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <p>Dashboard</p>
        </Header>
        <div className="dashboard_container">
          <Nav />
          <div className={styles.overview_body_container}>
            <h4>Modifica User</h4>
            <br />

            <div className="form_container d-flex flex-row justify-content-between primary_background border_primary p-4 align-items-start border-radius-15 position-relative">
              <div className={FormStyle.form_container}>
                <RoundedInput label="NOME" placeholder="Nome" />
                <RoundedInput label="COGNOME" />
                <RoundedInput label="EMAIL" />
                <RoundedInput label="TELEFONO" />
                <RoundedInput label="PASSWORD" type="password" />
                <RadioButtonContainer
                  name={"RUOLO"}
                  radioButtons={[
                    {
                      label: "ADMIN",
                      value: "ADMIN",
                    },
                    {
                      label: "CREATOR",
                      value: "CREATOR",
                    },
                  ]}
                />

                <Button
                  className={`position-absolute m-auto ${FormStyle.submit_button}`}
                  size="auto"
                >
                  SALVA{" "}
                </Button>
              </div>

              <Button fontSize="0.8em" size="auto">
                <AddIcon />

                <p
                  className="m-0"
                  style={{
                    marginLeft: "5px",
                  }}
                >
                  NUOVO USER
                </p>
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default modifieduser;
