import React from "react";
import Head from "next/head";
import Header from "../../components/molecules/Header";
import styles from "../../styles/Home.module.css";
import molecule from "../../styles/molecule.module.css";

function inviata(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>MCP- Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <p>Dashboard</p>
        </Header>
        <div className="body_container">
          <div className={molecule.recover_password}>
            <h4 className="underlined_text">INVIATA</h4>

            <p>
              {/* eslint-disable-next-line react/no-unescaped-entities */}
              Abbiamo inviato un'email per reimpostare la password <br />
              {/* eslint-disable-next-line react/no-unescaped-entities */}
              all'indirizzo di posta elettronica associato al tuo account <br />
              (Admin), la sua effettiva visualizzazione in Posta in Arrivo
              <br />
              potrebbe richiedere alcuni minuti. Per favore attendi almeno 10
              {/* eslint-disable-next-line react/no-unescaped-entities */}
              <br /> minuti prima di effettuare un'ulteriore richiesta.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

export default inviata;
