import Nav from "../../components/molecules/Nav";
import Header from "../../components/molecules/Header";
import styles from "../../styles/Home.module.css";
import Head from "next/head";

import Chart from "../../components/molecules/Overview/Chart";
import SecondContainer from "../../components/molecules/Overview/SecondContainer";
import Table from "../../components/molecules/Overview/Table";

function overview(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>MCP- Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <p>Dashboard</p>
        </Header>
        <div className="dashboard_container">
          <Nav />
          <div className={styles.overview_body_container}>
            <Chart />
            <SecondContainer />
            <Table />
          </div>
        </div>
      </main>
    </div>
  );
}

export default overview;
