export const resoProdotti = [
    {
      header: "Diritto di Recesso",
      desc: "Il diritto di recedere dal contratto concluso con la MCS Progetto Igiene di Amore Floreana, è esercitabile senza alcuna penalità entro quattordici (14) giorni dal giorno del ricevimento dei prodotti acquistati su www.mcsgroupsrl.com Per recedere dal contratto occorre inviare un’e-mail all’indirizzo mcsgroupsrl@gmail.com indicando chiaramente le generalità, il numero d’ordine, gli articoli resi e le motivazioni del reso. Le spese di spedizione sono a carico del cliente, ivi compresa la responsabilità in caso di smarrimento o danneggiamento dei prodotti Il Diritto di Recesso – oltre al rispetto dei termini e delle modalità sopra descritte, si intende esercitato correttamente qualora siano interamente rispettate anche le seguenti condizioni:  • l’e-mail deve essere correttamente compilata e trasmessa a mcsgroupsrl@gmail.com entro 14 giorni dal ricevimento dei prodotti; • i prodotti non devono essere stati utilizzati, lavati o danneggiati;       • i prodotti devono essere restituiti integri, non utilizzati e nella loro confezione originale;       • i prodotti resi devono essere inviati alla MCS Progetto Igiene di Amore Floreana in una sola spedizione in quanto la stessa si riserva il diritto di non accettare prodotti di uno stesso ordine, resi e spediti in momenti diversi.   Se il Diritto di Recesso è esercitato seguendo le modalità ed i termini indicati in questo paragrafo, la MCS Progetto Igiene di Amore Floreana provvede a rimborsare le eventuali somme già incassate per l’acquisto dei prodotti, al netto delle spese di spedizione per la consegna dei prodotti acquistati. Le somme saranno rimborsate nel minore tempo possibile ed, in ogni caso, entro quindici (15) giorni dalla data in cui la MCS Progetto Igiene di Amore Floreana è venuta a conoscenza dell’esercizio del diritto di recesso.        Qualora non siano rispettati le modalità ed i termini per l’esercizio del diritto di recesso, come specificato in questo paragrafo, non si avrà diritto al rimborso delle somme già corrisposte alla MCS Progetto Igiene di Amore Floreana; tuttavia si potranno riottenere, a spese del cliente, i prodotti nello stato in cui sono stati restituiti alla MCS Progetto Igiene di Amore Floreana.  In caso contrario, la MCS Progetto Igiene di Amore Floreana potrà trattenere i prodotti, oltre alle somme già pagate per il loro acquisto. ",
    },
    {
        header: "Restituzione Merce/Resi",
        desc: "In tutti i casi di restituzione della merce, le spese di trasporto sono a carico del Cliente. Fatto salvo per la restituzione di merce difettosa in garanzia nel qual caso le spese di riconsegna per la sostituzione del prodotto sono a carico della MCS Progetto Igiene di Amore Floreana."
    }
]