export const initialState = {
  first_name: "",
  last_name: "",
  company_name: "",
  address1: "",
  address2: "",
  city: "",
  state: "",
  post_code: "",
  country: "",
  phone: 0,
  email: "",
  tax_id_code: "",
  vat_number: "",
  unique_code: "",
  pec: "",
  reference_person: "",
  house_no: "",
  recipient_code: "",
  fax: "",
  cap: "",
  is_company: 0,
};
