import React from "react";
import Head from "next/head";
import PropTypes from "prop-types";
import Header from "./Header";
import Nav from "./Nav";
import styles from "../../styles/Home.module.css";

NavHeader.defaultProps = {
  title: "Dashbaord",
  page: "Home",
};

NavHeader.propType = {
  title: PropTypes.string,
  page: PropTypes.string,
};
function NavHeader({ title, children, page }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>MCP- Application - {page}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <p
            style={{
              margin: "0px",
            }}
          >
            {title}
          </p>
        </Header>
        <div className="dashboard_container">
          <Nav />
          {children}
        </div>
      </main>
    </div>
  );
}

export default NavHeader;
