import Nav from "../components/molecules/Nav";
import Header from "../components/molecules/Header";
import styles from "../styles/Home.module.css";
import Head from "next/head";

function overview(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>MCP- Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <p>Dashboard</p>
        </Header>
        <div className="dashboard_container">
          <Nav />
          <div className={styles.overview_body_container}>
            <div className={styles.chart_container}></div>
            <div className={styles.second_container}></div>
            <div className={styles.table}></div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default overview;
