import styles  from '../../styles/Home.module.css'
import Head from 'next/head'
import Header from '../../components/molecules/Header'
import Nav from '../../components/molecules/Nav'
import productCss from '../../styles/prodotti/prodotti.module.css'
import { useFormik } from 'formik';
// import { Formik, Form, useField } from 'formik';
// import TextArea from '../../components/atoms/form/formElements'

export default function prodotti(){

   
        const formik = useFormik({
          initialValues: {
            email: '',
          },
          onSubmit: values => {
            alert(JSON.stringify(values, null, 2));
          },
        });


    return(
        <>
    <div className={styles.container}>
      <Head>
        <title>MCP- Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <p>Dashboard</p>
        </Header>
        <div className="dashboard_container">
          <Nav />
          <div className={styles.overview_body_container}>
            <h2>Aggiungi Prodotto</h2>
            <div className={productCss.formWrapper}>
                
            <form onSubmit={formik.handleSubmit}>
                <div className={productCss.formInputSection}>
                    <h3 className={productCss.formSectionH3}>Info Generiche</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                            <label htmlFor="email">Email Address</label>
                            <input
                                id="email"
                                name="email"
                                type="email"
                                className='form-control'
                                onChange={formik.handleChange}
                                value={formik.values.email}
                            />
                        </div>

                        <div className={productCss.input}>
                            <label htmlFor="email">Descrizione</label>
                            <textarea
                            row="6"
                            className='form-control'
                            >
                            </textarea>
                        </div>

                        <div className={productCss.input}>
                            
                            <label htmlFor="email">Brand (Marca)</label>
                                <select className='custom-select form-control' id="inputGroupSelect01">
                                    <option selected>Choose...</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                        </div>

                    </div>

                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Info Generiche</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                            <label htmlFor="email">Email Address</label>
                            <input
                                id="email"
                                name="email"
                                type="email"
                                className='form-control'
                                onChange={formik.handleChange}
                                value={formik.values.email}
                            />
                        </div>

                        <div className={productCss.input}>
                            <label htmlFor="email">Descrizione</label>
                            <textarea
                            row="6"
                            className='form-control'
                            >
                            </textarea>
                        </div>

                        <div className={productCss.input}>
                            
                            <label htmlFor="email">Brand (Marca)</label>
                                <select className='custom-select form-control' id="inputGroupSelect01">
                                    <option selected>Choose...</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                        </div>
                    </div>
                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Info Generiche</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                            <label htmlFor="email">Email Address</label>
                            <input
                                id="email"
                                name="email"
                                type="email"
                                className='form-control'
                                onChange={formik.handleChange}
                                value={formik.values.email}
                            />
                        </div>

                        <div className={productCss.input}>
                            <label htmlFor="email">Descrizione</label>
                            <textarea
                            row="6"
                            className='form-control'
                            >
                            </textarea>
                        </div>

                        <div className={productCss.input}>
                            
                            <label htmlFor="email">Brand (Marca)</label>
                                <select className='custom-select form-control' id="inputGroupSelect01">
                                    <option selected>Choose...</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                        </div>
                    </div>
                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Info Generiche</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                            <label htmlFor="pdf">PDF</label>
                            <input
                                id="pdf"
                                name="pdf"
                                type="file"
                                className='form-control'
                                onChange={formik.handleChange}
                                value={formik.values.email}
                            />
                        </div>
                    </div>
                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Info Generiche</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                            <label htmlFor="image">Immagine</label>
                            <input
                                id="image"
                                name="image"
                                type="file"
                                className='form-control'
                                onChange={formik.handleChange}
                                value={formik.values.email}
                            />
                        </div>
                    </div>
                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Categoria</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                                <label htmlFor="categoria">Seleziona Categoria</label>
                                <select className='custom-select form-control' id="categoria">
                                    <option selected>Choose...</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                        </div>
                    </div>
                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Tag</h3>
                    <div className={productCss.formInputWrapper}>
                        <div className={productCss.input}>
                        <label htmlFor="tag">Aggiungi Tag (#)</label>
                            <input
                                id="tag"
                                name="tag"
                                type="file"
                                className='form-control'
                                onChange={formik.handleChange}
                                value={formik.values.tag}
                            />
                        </div>
                    </div>
                </div>

                <div className={productCss.formInputSection}>
                <h3 className={productCss.formSectionH3}>Status</h3>
                    <div className={productCss.formInputWrapper}>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="inlineRadio1" value="option1" />
                            <label class="form-check-label" for="inlineRadio1">Attiva</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="inlineRadio2" value="option2" />
                            <label class="form-check-label" for="inlineRadio2">Bozza</label>
                        </div>                    
                    </div>
                </div>


           

                <button type="submit">Submit</button>
            </form>
            </div>
          </div>
        </div>
      </main>
    </div>
        </>
    )
}